const DashboardView = (function () {
  function renderDashboardPage(container,state){
    const user=state.user||{}; const m=state.metrics||{}; const scores=state.assessment?.pillarScores||{}; const avg=Object.values(scores).length?Math.round(Object.values(scores).reduce((a,b)=>a+Number(b),0)/4):0; const lowest=state.assessment?.lowestPillarName||'Belum ada assessment'; const ch=state.challenge; const adaptive=state.adaptive||{}; const challengeDone=!!ch && Array.isArray(ch.days) && ch.days.length>0 && ch.days.every(d=>d.value!==null && d.value!=='');
    container.innerHTML=`<div class="mb-4"><h1 class="display-6 fw-bold mb-1">Halo, ${user.name||'Teman'} 👋</h1><p class="text-muted">Ini ringkasan perjalanan kesehatanmu saat ini.</p></div>
      <div class="row g-3 mb-4"><div class="col-md-4"><div class="vitabyte-card h-100"><div class="small text-muted fw-semibold">BMI</div><div class="display-6 fw-bold text-success mt-2">${m.bmi||'—'}</div><span class="badge bg-success-subtle text-success border">${m.bmiCategory||'Belum dihitung'}</span><p class="small text-muted mt-2 mb-0">BMI adalah informasi tambahan, bukan diagnosis.</p></div></div>
      <div class="col-md-4"><div class="vitabyte-card h-100"><div class="small text-muted fw-semibold">HEALTH SCORE</div><div class="display-6 fw-bold mt-2">${avg||'—'}${avg?'/100':''}</div><div class="small text-secondary mt-2">Fokus: ${lowest}</div></div></div>
      <div class="col-md-4"><div class="vitabyte-card h-100"><div class="small text-muted fw-semibold">🔥 KONSISTENSI</div><div class="display-6 fw-bold mt-2">${state.streak||0}</div><div class="small text-secondary">hari terbaik tercatat</div></div></div></div>
      <div class="vitabyte-card-mint border-emerald mb-4"><span class="eyebrow-label">ADAPTIVE TIP</span><h5 class="fw-bold mt-1">${adaptive.recommendation||'Mulai dengan Assessment untuk mendapatkan rekomendasi personal.'}</h5><p class="small text-secondary mb-0">${adaptive.reason||'Sistem akan menyesuaikan langkah berdasarkan progres tracking.'}</p></div>
      <div class="row g-4"><div class="col-md-6"><div class="vitabyte-card h-100"><h5 class="fw-bold">🩺 Health Assessment</h5><p class="small text-secondary">Jawab 16 pertanyaan untuk mendapatkan skor empat pilar.</p><a href="assessment.html" class="btn btn-emerald w-100">Mulai Assessment →</a></div></div>
      <div class="col-md-6"><div class="vitabyte-card h-100"><h5 class="fw-bold">📚 Learning Center</h5><p class="small text-secondary">Pelajari pilar yang paling membutuhkan perhatian dan dapatkan tips praktis.</p><a href="learn-specific.html" class="btn btn-emerald w-100">Buka Learning Center →</a></div></div>
      <div class="col-md-6"><div class="vitabyte-card h-100"><h5 class="fw-bold">🏆 Challenge & Tracking</h5><p class="small text-secondary">Latih satu kebiasaan kecil selama tujuh hari dan catat hasilnya.</p><a href="challenge-hub.html" class="btn btn-emerald w-100">Buka Challenge →</a></div></div>
      <div class="col-md-6"><div class="vitabyte-card h-100"><h5 class="fw-bold">🔄 Re-Check</h5><p class="small text-secondary">${challengeDone ? 'Challenge 7 hari selesai. Sekarang ukur kembali kondisimu untuk melihat perubahan.' : 'Selesaikan Challenge 7 hari terlebih dahulu. Setelah itu kamu bisa melakukan Re-Check.'}</p>${challengeDone ? '<a href="post-test.html" class="btn btn-outline-emerald w-100">Buka Re-Check →</a>' : '<button class="btn btn-outline-secondary w-100" disabled>🔒 Terkunci sampai Day 7</button>'}</div></div></div>`;
  }
  return {renderDashboardPage};
})();
